// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entity_example;

#nullable disable

namespace entity_example.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20221016094825_Addingassetnew1table")]
    partial class Addingassetnew1table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POffices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("PPurcdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ptype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("locPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Assetnew1");
                });
#pragma warning restore 612, 618
        }
    }
}
