// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entity_example;

#nullable disable

namespace entity_example.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20221016100351_addingvaluestotable")]
    partial class addingvaluestotable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POffices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("PPurcdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ptype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("locPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Assetnew1");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            PBrand = "Samsung",
                            PCurrency = "EUR",
                            PModel = "S10",
                            POffices = "Spain",
                            PPrice = 6000.0,
                            PPurcdate = new DateTime(2020, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ptype = "Mobile",
                            locPrice = 6179f
                        },
                        new
                        {
                            Id = 3,
                            PBrand = "Iphone",
                            PCurrency = "EUR",
                            PModel = "I20",
                            POffices = "Spain",
                            PPrice = 4000.0,
                            PPurcdate = new DateTime(2019, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ptype = "Mobile",
                            locPrice = 4030f
                        },
                        new
                        {
                            Id = 4,
                            PBrand = "Azure",
                            PCurrency = "SEK",
                            PModel = "AX2",
                            POffices = "Sweden",
                            PPrice = 7000.0,
                            PPurcdate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ptype = "Computer",
                            locPrice = 79468f
                        },
                        new
                        {
                            Id = 5,
                            PBrand = "Lava",
                            PCurrency = "SEK",
                            PModel = "LX2",
                            POffices = "Sweden",
                            PPrice = 7000.0,
                            PPurcdate = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ptype = "Mobile",
                            locPrice = 79468f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
